### PR TITLE
new: sima9zページ対応

### PR DESCRIPTION
**Pull request by sima9z**
# PRの内容
※[ ]の中の空欄を消してxを入れてチェックしてください

- [x] 自己紹介ページの作成・編集

- [ ] ファイル・フォルダの作成・編集(自己紹介以外)

- [ ] その他(内容は下に書いてください)

### 変更点・追加したフォルダやファイルの内容
具体的な変更点や修正箇所を箇条書きでリストアップしてください。

- pages/members内にsima9z.tsxを作成しました。
- components内にsima9zフォルダを作成し、さらにその中にHeadSection.tsx、ProfileSection.tsx、CreateApplicationsSection.tsx、ReusableCard.tsx、Theme.tsを作成しました。
- typesフォルダ内にtypes_sima9z.tsを作成しました。
- publicフォルダ内にsima9zフォルダを作成し、さらにその中にstrawberry_frame.png、profile.jpg、dagasiya.png、hosinozukan.png、virtualpet.pngを配置しました。

### 追加・変更した理由

- 個人ページ対応のため。

### その他、報告事項

特にないです。

### CODE REVIEW

**Comment by n-katou** [comment]
./components/sima9z/ReusableCard.tsx:30:8
Type error: No overload matches this call.
  Overload 1 of 3, '(props: { href: string; } & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<Omit<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, "ref"> & { ...; }, "className" | ... 24 more ... | "startIcon">): Element', gave the following error.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 3, '(props: { component: ElementType<any, keyof IntrinsicElements>; } & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>): Element | null', gave the following error.
    Property 'component' is missing in type '{ children: Element; href: string | undefined; onClick: (() => void) | undefined; target: string; rel: string; }' but required in type '{ component: ElementType<any, keyof IntrinsicElements>; }'.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<ButtonTypeMap<{}, "button">>>): Element | null', gave the following error.
    Type '{ children: Element; href: string | undefined; onClick: (() => void) | undefined; target: string; rel: string; }' is not assignable to type 'IntrinsicAttributes & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
      Property 'target' does not exist on type 'IntrinsicAttributes & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
  28 |         style={{ borderRadius: '15px' }}
  29 |       />
> 30 |       <Button         
     |        ^
  31 |         href={link !== '#' ? link : undefined} 
  32 |         onClick={link === '#' ? onClick : undefined} 
  33 |         target="_blank" 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

遅くなり申し訳ないです。
エラー内容貼っときます！

**Comment by n-katou** [comment]
あとネキのページだと、ヘッダーのボタンから遷移が効かなくなるから
そこも確認お願いします。

**Comment by sima9z** [comment]
すみません、対応しましたが再度デプロイエラーのようです…
確認の程よろしくお願いします。

**Comment by n-katou** [comment]
Failed to compile.
./pages/members/sima9z.tsx:7:25
Type error: File name '/vercel/path0/web/components/sima9z/headSection.tsx' differs from already included file name '/vercel/path0/web/components/sima9z/HeadSection.tsx' only in casing.
  The file is in the program because:
    Root file specified for compilation
    Imported via '../../components/sima9z/HeadSection' from file '/vercel/path0/web/pages/members/sima9z.tsx'
    Root file specified for compilation
   5 | import { ThemeProvider } from '@mui/material/styles';
   6 |
>  7 | import HeadSection from '../../components/sima9z/HeadSection'
     |                         ^
   8 | import ProfileSection from '../../components/sima9z/ProfileSection'
   9 | import Links from '../../components/sima9z/Links'
  10 | import CreateApplicationsSection from '../../components/sima9z/CreateApplicationsSection'
error Command failed with exit code 1.

**Comment by n-katou** [comment]
Failed to compile.
./pages/members/sima9z.tsx:7:25
Type error: File name '/vercel/path0/web/components/sima9z/headSection.tsx' differs from already included file name '/vercel/path0/web/components/sima9z/HeadSection.tsx' only in casing.
  The file is in the program because:
    Root file specified for compilation
    Imported via '../../components/sima9z/HeadSection' from file '/vercel/path0/web/pages/members/sima9z.tsx'
    Root file specified for compilation
   5 | import { ThemeProvider } from '@mui/material/styles';
   6 |
>  7 | import HeadSection from '../../components/sima9z/HeadSection'
     |                         ^
   8 | import ProfileSection from '../../components/sima9z/ProfileSection'
   9 | import Links from '../../components/sima9z/Links'
  10 | import CreateApplicationsSection from '../../components/sima9z/CreateApplicationsSection'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

**Comment by n-katou** [comment]
Failed to compile.
./pages/members/sima9z.tsx:7:25
Type error: File name '/vercel/path0/web/components/sima9z/headSection.tsx' differs from already included file name '/vercel/path0/web/components/sima9z/HeadSection.tsx' only in casing.
  The file is in the program because:
    Root file specified for compilation
    Imported via '../../components/sima9z/HeadSection' from file '/vercel/path0/web/pages/members/sima9z.tsx'
    Root file specified for compilation
   5 | import { ThemeProvider } from '@mui/material/styles';
   6 |
>  7 | import HeadSection from '../../components/sima9z/HeadSection'
     |                         ^
   8 | import ProfileSection from '../../components/sima9z/ProfileSection'
   9 | import Links from '../../components/sima9z/Links'
  10 | import CreateApplicationsSection from '../../components/sima9z/CreateApplicationsSection'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

ずっと同じエラーだけど
ファイル名とインポート名は統一できてる？

**Comment by n-katou** [comment]
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

Expected server HTML to contain a matching <div> in <div>.


...
  <eval>
    <div>
    ^^^^^
      <Box>
        <eval>
          <div>
          ^^^^^
          
          http://localhost:4000/members/sima9z
          にアクセスすると上記のエラーが発生するから、対応お願いします。

**Comment by n-katou** [comment]
ヘッダーのボタン押せない＋ネキのXとGitHubのボタンを押しても
反応しないです！
ネキのローカルでは機能してる？

**Comment by sima9z** [comment]
> ヘッダーのボタン押せない＋ネキのXとGitHubのボタンを押しても 反応しないです！ ネキのローカルでは機能してる？

自分のローカルでは機能しています。
ただ押せるまで若干のタイムラグがあるようですがいかがでしょうか？

**Comment by n-katou** [comment]
タイムラグとかではなさそう。
そもそもボタンとて機能していない感じ。
他の人にも確認してもらいましょう。

**Review by rei-dev99 — APPROVED** [review]
LGTMです！
流石REACTの神！

微妙にヘッダーロゴとABOUTのホバーがしづらくなっていますが(画像が悪さしてる？検証モードで試しましたが不明)、お好みで頑張ってください〜！

**Comment by rei-dev99** [comment]
ヘッダーロゴ、ABOUT問題なくクリックできるようになりました！

**Review by n-katou — APPROVED** [review]
動作確認できたのでLGTMです！

**Pull request merged**
